[package]
name = "task-motel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = { version = "1.11", features = [ "full" ] }
tokio-stream = { version = "0.1", features = [ "sync" ] }
tracing = "0.1"

[dev-dependencies]
parking_lot = "*"
task-motel = { path = ".", features = ["test-util"]}

[features]
test-util = ["tokio/test-util"]